### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Shidoengie** [Shidoengie/Topdown#2]
## Enemy AI
- [x] Shooting
- [x] Path finding
- [x] Player awareness and player timer
- [ ] Player seeking

## Gameplay
- [x] Adding guns 
- [ ] More weapon options
- [ ] Fixing weapon stats
- [x] Ammo and reloading
- [x] Weapon aquisition 
- [x] #7
- [x] Auto weapons 
- [x] Health regen
 - [ ] Weapon weilding and unwield with key

##  Modding
- [x] Weapon stats modification from json
- [ ] Weapon addition 

## GUI 
- [x] Create a mockup of what the interface will look like
- [ ] Create icons
- [ ] Replace placeholder
- [ ] Weapon wheel

## Driving
- [ ] Adding cars
- [x] Car stats json
- [x] Car control
- [x] Car entering
- [ ] Player to Car nav

## Other

- [ ] Add main menu
- [ ] Make map
- [ ] Game saves
- [ ] Add more console commands
